# Generated by Django 3.1.14 on 2022-06-29 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_management', '0004_stuff'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Stuff',
            new_name='Staff',
        ),
    ]
