# Generated by Django 3.1.14 on 2022-07-02 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management', '0006_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
