# Generated by Django 3.1.14 on 2022-07-05 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management', '0008_staff_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff_notification',
            name='status',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
