# Generated by Django 3.1.14 on 2022-07-06 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management', '0011_auto_20220706_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff_leave',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='staff_notification',
            name='status',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
